version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${env.DB_USER}
      POSTGRES_PASSWORD: ${env.DB_PASSWORD}
      POSTGRES_DB: ${env.DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${env.DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${env.DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${env.DB_PASSWORD}

volumes:
  postgres_data:
